question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "California is larger than Japan.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "The Republic of Malta is the smallest microstate worldwide.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "Greenland is covered with grass and Iceland covered with ice.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "St. Louis is the capital of the US State Missouri.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "There are no deserts in Europe.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "Alaska is the largest state in the United States.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "Tokyo is the capital of Japan.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "Nova Scotia is on the east coast of Canada.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "Toronto is the capital city of the North American country of Canada.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "Hungary is the only country in the world beginning with H.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
